openapi: 3.0.1
info:
  title: Learning Swagger Documentations
  version: 1.0.0
servers:
  - url: http://localhost:4000/v1
    description: Local Server
  - url: https://staging.example.com/v1
    description: Staging Server
paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: health check
      responses:
        '200':
          description: OK
